prefix : <http://ns.inria.fr/sparql-micro-service/api#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX schema: <http://schema.org/#>
prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

CONSTRUCT {
    ?Place
        a schema:Place;
        schema:identifier ?placeId;
        schema:name ?placeName;
        schema:category ?categories;
        schema:city ?municipality;
        schema:country ?country;
        schema:countryCode ?countryCode;
        schema:freeFormAddress ?freeformAddress;
}

WHERE {
    [] :results [
            :type ?placeType;
            :id ?placeId;
            :poi [
                :name ?placeName;
                :categorySet [
                    :id ?categoryId;
                ];
                :categories ?categories;
            ];
            :address [
                :streetName ?streetName;
                :municipality ?municipality;
                :postalCode ?postalCode;
                :country ?country;
                :countryCode ?countryCode;
                :freeformAddress ?freeformAddress;
            ]
        ].
        # Bind the IRI for the hotel to a variable ?hotel
        BIND(IRI(CONCAT("http://example.org/hotel/", STR(?placeId))) AS ?Place)
}
